version: '3.5'

services:
  database:
    restart: always
    image: postgres:16-alpine
    env_file:
      - path: .env
        required: true
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
